# Copyright (c) Arthur Diniz <arthurbdiniz@gmail.com>
# SPDX-License-Identifier: Apache-2.0

version: '3.7'
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:1.84.1
    ports:
      - "5678:5678"
    environment:
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: false
      N8N_RUNNERS_ENABLED: true
    volumes:
      - ../testdata/config:/home/node/.n8n/config
      - ../testdata/database.sqlite:/home/node/.n8n/database.sqlite
