name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Format
        run: gofmt -s -w -e .

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          only-new-issues: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: go install -v ./...

      - name: Build
        run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run Tests
        run: go test -v -cover -timeout=120s -parallel=10 ./...

  testacc:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run Acceptance Tests
        run: TF_ACC=1 go test -v -cover -timeout 120m ./...
